chapters/03-package-setup.Rmd

A stab at the final exercise with a lot of `FIXME`s for specific details to be filled in.

Final exercise for Package Setup

---

chapters/05-version-control-solo.Rmd
chapters/11-version-control-workflow.Rmd

@k8hertweck I moved an item over from your Git as solo chapter, since it seemed to make more sense here.

First draft of final exercise for GitHub workflows (chapter 11)

---

chapters/04-function-development.Rmd

Very rough, but basic idea is to add two functions to the package: one based on a snippet of code we provide, and one that is only described through functionality and learner needs to figure out code.
Both will need some basic docs, and probably figuring some dependency issues (e.g. snippet might use a function from another package).
Would be really nice if second function requires calling first function to demonstrate building up more complicated functionality, but will depend on final project.
My only concern is, is two functions too much at this stage?  Should we limit it to one...then maybe have some optional extensions.

Final Exercise for Function development in a package environment

---

chapters/06-code-correctness.Rmd

I went on the rather vague side of things on this one.  Main goal is to encourage exploring expectations beyond `expect_equal()` and practice workflow.

Draft final exercises for code correctness

---

chapters/14-team-package-dev.Rmd

Finished a draft of the final exercise.

Final exercise for Chapter 14: Working in a team environment

---

chapters/08-documentation.Rmd

This is pretty much just a list of the learning goals for this chapter in exercise form.

Add skeleton final exercises for documentation chapter

---

chapters/10-community-involvement.Rmd

In brief, these exercises have the learner:
- Review README for jargon 
- Create CODE-OF-CONDUCT, CONTRIBUTING, LICENSE, and NEWS
I referred heavily to Mozilla's [Open Leadership Training material](https://mozilla.github.io/open-leadership-training-series/articles/readme/) which I think is excellent. 
Where applicable I use `usethis` functions, but I'm not sure if I got all the right ones - feedback appreciated!

First draft of final exercises for community involvement (chapter 10)

---

chapters/02-filesystem.Rmd

These exercises could easily be expanded to include other tasks that are conceptual and not directly related to the project assignment. I would like to revise these once we've settled on exercises for other chapters, and have identified conceptually challenging things that pop up later in the book.
One big question I have is whether we'll be using the shell extensively in the rest of the book. This would inform whether we should include exercises explicitly about using those commands.

02 filesystem questions + exercises

---

chapters/05-version-control-solo.Rmd

Two groups of exercises here:
- one set asking for working with history and branches, using the example project from the narrative
- one set focused on the project assignment

05-version-control-solo

---

chapters/12-project-management.Rmd

I don't think all of these steps are required for every open project, but maybe we want them as exercises for the learning benefit? I worry that if they are clearly overkill, learners won't be interested in doing them. The answer to this will probably become apparent as we flesh out what the final assignment package looks like.

First draft of final exercises for project-management (chapter 12)

---

chapters/09-package-website.Rmd

This PR adds the draft for the final exercise for chapter 09. It includes one optional exercise which we can then delete if we think it's too out of scope.

Adding chapter 09 final exercise draft

---

chapters/13-package-release.Rmd

This PR adds the draft for the final exercise for chapter 13. It includes two optional exercises which we can then delete if we think they are too out of scope.

Chapter 13 final draft exercise

---

chapters/03-package-setup.Rmd

Following general structure of @mbonsma for this, with one exception, I added "Exercise:" where I thought a core exercise might appear.

Rough outline of Package Setup

---

CONTRIBUTING.md
README.md
appendices/assignments.md
appendices/templates.Rmd
appendices/trivia.Rmd
chapters/01-preface.Rmd
chapters/13-package-release.Rmd
index.Rmd

Closes #73
@k8hertweck you want to review and merge when you approve?

Switch course to book

---

index.Rmd

Closes #74.
@k8hertweck you said this much better than what I wrote. Can you edit and merge afterwards?

Start of motivation for book section

---

chapters/02-filesystem.Rmd

This chapter remains really difficult to frame, since none of the things here are actually used for pushing the final project ahead. Moreover, I checked the current status of the two projects (zipfs and kenyaweather) and very few of the functions from {fs} are used in them (though that may change). Ideally we'd demonstrate a few functions from each of the three sections of {fs}, but I also don't think we should take more time to cover something that we won't be doing comprehensively. 
I tried to reinforce in the narrative that this is more about making sure we're all on the same page about organization and tools to use while developing code (rather than actually developing the code itself), but I'm open to suggestions about parameterizing it further. 
Since this is the first chapter in …

Chapter 2 detailed outline: filesystem and R projects

---

chapters/13-package-release.Rmd

This PR includes the outline for chapter 13. In my opinion it is a little bit short so if people want to chime in with ideas I'm more than open to include them.

Chapter 13 Outline

---

chapters/05-version-control-solo.Rmd
chapters/11-version-control-workflow.Rmd

There are still a few things that are fuzzy regarding scope of this chapter, since it covers three different ways of interacting with git (including the need for screenshots, which will make this chapter lengthy) as well as overlap with the later chapter on workflows in git.
In particular:
- We should probably move the section on Securing your GitHub in the second git chapter to the first Git chapter, since that's where github is introduced. Alternatively, we could add this content to an appendix.
- It's not clear how much this chapter should cover using GitHub (e.g., orientation to GitHub, and editing files on it). These weren't initially mentioned in the outline, but in retrospect, I think it would be good to include them here (so we could also show making changes remotely and pulling …

05-solo version control objectives and activity outline

---

chapters/08-documentation.Rmd

Incremental drafting of chapter 8

Chapter 8 - documentation

---

chapters/10-community-involvement.Rmd

First few sections drafted, still a ways to go!

Text for chapter 10

---

CONTRIBUTING.md
README.md
chapters/03-package-setup.Rmd
chapters/11-version-control-workflow.Rmd

Plus reformat to quarto style. The pak package is just better at installing packages than the remotes package.

Use pak instead of remotes

---

CONTRIBUTING.md
_admin/markdown.snippets
appendices/resources.qmd
chapters/01-preface.Rmd
chapters/03-package-setup.Rmd

Some support items
- RStudio markdown snippets file to use for helping build book
- Example code using `usethis::with_project()` to create package, run git, etc within a temp folder.

Support infrastructure

---

chapters/13-team-package-dev.Rmd

Chapter 13 draft
